export enum TransactionCategory {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

export enum TransactionType {
  HOUSING = 'HOUSING',
  TRANSPORTATION = 'TRANSPORTATION',
  FOOD = 'FOOD',
  UTILITIES = 'UTILITIES',
  CLOTHING = 'CLOTHING',
  HEALTHCARE = 'HEALTHCARE',
  INSURANCE = 'INSURANCE',
  PERSONAL = 'PERSONAL',
  DEBT = 'DEBT',
  SAVINGS = 'SAVINGS',
  EDUCATION = 'EDUCATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  MISCELLANEOUS = 'MISCELLANEOUS',
  SALARY = 'SALARY',
  BUSINESS = 'BUSINESS',
  GIFT = 'GIFT',
  INVESTMENT = 'INVESTMENT',
  REFUND = 'REFUND',
  TAXES = 'TAXES',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
}

export enum currency {
  NGN = 'NGN',
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  SEK = 'SEK',
  NZD = 'NZD',
  NOK = 'NOK',
  RUB = 'RUB',
  SGD = 'SGD',
  HKD = 'HKD',
  KRW = 'KRW',
  BRL = 'BRL',
  ZAR = 'ZAR',
  INR = 'INR',
  TRY = 'TRY',
  AED = 'AED',
  ARS = 'ARS',
  BDT = 'BDT',
  CLP = 'CLP',
  COP = 'COP',
  EGP = 'EGP',
  FJD = 'FJD',
  GHS = 'GHS',
  HUF = 'HUF',
  IDR = 'IDR',
  ILS = 'ILS',
  JMD = 'JMD',
  KES = 'KES',
  LKR = 'LKR',
  MAD = 'MAD',
  MMK = 'MMK',
  MUR = 'MUR',
  NIO = 'NIO',
  OMR = 'OMR',
  PAB = 'PAB',
  PEN = 'PEN',
  QAR = 'QAR',
  RWF = 'RWF',
  SBD = 'SBD',
  TTD = 'TTD',
  UGX = 'UGX',
  VND = 'VND',
  YER = 'YER',

}

export enum UserType {
  ADMIN = 'ADMIN',
  USER = 'USER',
}